import Head from 'next/head';

import { createClient } from '@remixproject/plugin-webview';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    const client = createClient();
    client.onload(async () => {
      const data = client.call('fileManager', 'readFile', 'README.txt');
      console.log('loaded', data);

      client.on('fileManager', 'currentFileChanged', (fileName: string) => {
        console.log('currentFileChanged', fileName);
      });

      client.solidity.on(
        'compilationFinished',
        (
          fileName: string,
          source: string,
          languageVersion: string,
          data: any,
        ) => {
          console.log(
            'compilationFinished',
            fileName,
            // source,
            // languageVersion,
            data,
          );
        },
      );

      client.udapp.on('newTransaction', (tx: any, receipt: any) => {
        console.log('newTransaction', { tx, receipt });

        if (!tx.to) {
          console.log('contract creation', {
            chainId: tx.chainId,
            blockNumber: tx.blockNumber,
            contractAddress: receipt.contractAddress,
          });
        }
      });
    });
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello world</main>
    </>
  );
}
